name: mada_server
description: A web server built using the shelf package.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0  
  json_annotation: ^4.0.1
  openapi_base: any
  dart_numerics: ^0.0.2
  

dev_dependencies:
  pedantic: ^1.10.0 
  openapi_code_builder: any
  json_serializable: ^4.1.3
  build_runner: ^1.10.0
